from django.urls import path
from .views import (
    admin_categories,
    admin_dashboard_data,
    admin_me,
    admin_options_list,
    admin_options_manage,
    admin_user_avatar_delete,
    admin_user_list,
    admin_user_update,
    admin_user_view,
    clothing_items,
    clothing_item_detail,
    get_or_create_profile,
    remove_item_from_wardrobe,
    wardrobe_detail,
    wardrobe_items,
    wardrobes,
    outfits,
    outfit_detail,
    explore_outfits,
    toggle_save_outfit,
    get_saved_outfits,
)

urlpatterns = [
    path("profile/", get_or_create_profile),
    path("clothing-items/", clothing_items),
    path("clothing-items/<int:item_id>/", clothing_item_detail),
    path("wardrobes/", wardrobes),
    path("wardrobes/<int:wardrobe_id>/", wardrobe_detail),
    path("wardrobes/<int:wardrobe_id>/items/", wardrobe_items),
    path(
        "wardrobes/<int:wardrobe_id>/items/<int:item_id>/",
        remove_item_from_wardrobe,
    ),
    path("outfits/", outfits),
    path("outfits/explore/", explore_outfits),
    path("outfits/<int:outfit_id>/", outfit_detail),
    path("outfits/<int:outfit_id>/toggle_save/", toggle_save_outfit),
    path("outfits/saved/", get_saved_outfits),
    path("admin/dashboard-data/", admin_dashboard_data),
    path("admin/me/", admin_me),
    path("admin/categories/", admin_categories),
    path("admin/options/", admin_options_list),
    path("admin/options/manage/", admin_options_manage),
    path("admin/options/manage/<int:option_id>/", admin_options_manage),
    path("admin/users/", admin_user_list),
    path("admin/users/<str:firebase_uid>/", admin_user_update),
    path("admin/users/<str:firebase_uid>/avatar/", admin_user_avatar_delete),
    path("admin/users/<str:firebase_uid>/details/", admin_user_view),
]
