# Generated by Django 6.0.1 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(default='Free', max_length=50)),
                ('wardrobe_count', models.IntegerField(default=0)),
                ('wardrobe_limit', models.IntegerField(default=100)),
                ('outfits_count', models.IntegerField(default=0)),
                ('outfits_limit', models.IntegerField(default=200)),
                ('style_points', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
