# Generated by Django 6.0.1 on 2026-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clothingitem_wardrobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='occasion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='clothing_item_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('category', ''), _negated=True), name='clothing_item_category_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('season', ''), _negated=True), name='clothing_item_season_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('occasion', ''), _negated=True), name='clothing_item_occasion_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('size', ''), _negated=True), name='clothing_item_size_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('material', ''), _negated=True), name='clothing_item_material_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('brand', ''), _negated=True), name='clothing_item_brand_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('image', ''), _negated=True), name='clothing_item_image_not_empty'),
        ),
    ]
