# Generated by Codex on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_clothingitem_brand_alter_clothingitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="purchase_store",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
