# Generated by Django 6.0.1 on 2026-03-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('category', 'Category'), ('season', 'Season'), ('occasion', 'Occasion'), ('size', 'Size'), ('material', 'Material')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
    ]
