# Generated by Django 6.0.1 on 2026-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_outfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(max_length=100),
        ),
    ]
