# Generated by Django 6.0.1 on 2026-03-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_outfit_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='purchase_store',
        ),
    ]
