# Generated by Django 6.0.1 on 2026-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_clothingitem_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
