# Generated by Django 6.0.1 on 2026-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_outfit_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_outfits', to='users.profile'),
        ),
    ]
