# Generated by Django 6.0.1 on 2026-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='layer_level',
            field=models.IntegerField(default=0),
        ),
    ]
