# Generated by Django 6.0.1 on 2026-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_clothingitem_color_hex_clothingitem_layer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='item_type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Bag', 'Bag'), ('Undergarment', 'Undergarment')], default='Top', max_length=50),
        ),
    ]
