# Generated by Django 6.0.1 on 2026-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_clothingitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingoption',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Bag', 'Bag'), ('Undergarment', 'Undergarment')], help_text='Required for Category type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clothingoption',
            name='layer_level',
            field=models.IntegerField(default=0, help_text='0: Base, 1: Mid, 2: Outer. For Tops.'),
        ),
    ]
