# Generated by Django 6.0.1 on 2026-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_clothingoption_item_type_clothingoption_layer_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingoption',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('season', 'Season'), ('occasion', 'Occasion'), ('size', 'Size'), ('material', 'Material'), ('color', 'Color')], max_length=20),
        ),
    ]
