# Generated by Django 6.0.1 on 2026-04-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_clothingitem_color_hex_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='purchase_link',
            field=models.URLField(blank=True, help_text='External link to buy the item', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Set by admin to show verified/featured badge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, help_text="e.g. {'instagram': '@user', 'tiktok': '@user'}", null=True),
        ),
        migrations.AlterField(
            model_name='clothingoption',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('season', 'Season'), ('occasion', 'Occasion'), ('size', 'Size'), ('material', 'Material'), ('color', 'Color'), ('weather', 'Weather')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='users.profile')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='users.wardrobe')),
            ],
        ),
    ]
