# Generated by Django 6.0.1 on 2026-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_profile_currency_featuredwardroberequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredwardroberequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuredwardroberequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
