# Generated by Django 6.0.1 on 2026-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_featuredwardroberequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_stylist_usage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
