# Generated by Django 6.0.1 on 2026-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_last_stylist_usage_alter_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_analysis_usage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
