# Generated by Django 6.0.1 on 2026-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_last_analysis_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
