# Generated by Django 6.0.1 on 2026-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Superadmins cannot be demoted by regular admins'),
        ),
    ]
