# Generated by Django 6.0.1 on 2026-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredwardroberequest',
            name='khalti_pidx',
            field=models.CharField(blank=True, help_text='Khalti Payment ID (pidx)', max_length=255, null=True),
        ),
    ]
