# Generated by Django 6.0.1 on 2026-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_featuredwardroberequest_khalti_pidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredwardroberequest',
            name='khalti_mobile',
            field=models.CharField(blank=True, help_text='Mobile used for payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='featuredwardroberequest',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, help_text='Khalti Transaction ID from lookup', max_length=255, null=True),
        ),
    ]
