# Generated by Django 6.0.1 on 2026-04-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_featuredwardroberequest_khalti_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='featured_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.featuredwardroberequest'),
        ),
        migrations.AlterField(
            model_name='report',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.outfit'),
        ),
    ]
