# Generated by Django 6.0.1 on 2026-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_report_featured_request_alter_report_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='Optional additional context from the reporter', null=True),
        ),
    ]
