# Generated by Django 6.0.1 on 2026-04-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_report_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='outfits_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='outfits_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wardrobe_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wardrobe_limit',
        ),
    ]
